apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: library-management
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: library-eureka-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: SERVER_PORT
          value: "8761"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://config-server.library-management.svc.cluster.local:8888/"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 30
      initContainers:
      - name: wait-for-config
        image: busybox:1.35
        command: ['sh', '-c', 'until wget -q --tries=1 --timeout=2 --spider http://config-server.library-management.svc.cluster.local:8888/actuator/health; do echo waiting for config-server; sleep 5; done']
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: library-management
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
  - name: http
    port: 8761
    targetPort: 8761
    protocol: TCP
  type: ClusterIP
