apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: library-management
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: library-user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: SERVER_PORT
          value: "8081"
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://config-server.library-management.svc.cluster.local:8888/"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server.library-management.svc.cluster.local:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: library-config
        - secretRef:
            name: library-secrets
        resources:
          requests:
            memory: "768Mi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 30
      initContainers:
      - name: wait-for-eureka
        image: busybox:1.35
        command: ['sh', '-c', 'until wget -q --tries=1 --timeout=2 --spider http://eureka-server.library-management.svc.cluster.local:8761/actuator/health; do echo waiting for eureka-server; sleep 5; done']
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: library-management
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
