server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.library-management.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: 
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            maxAge: 3600

logging:
  level:
    com.library: INFO
    org.springframework.cloud.gateway: INFO
    root: INFO
